//! Parameter registry accessor (spec/DOCS-parameters.md). The generated
//! `params.json` is compiled in; nothing in `src/` holds a tunable literal.
use bevy::prelude::Resource;
use serde::Deserialize;
use std::collections::HashMap;

/// One registry entry as generated by `tools/gen_params.py`.
#[derive(Deserialize, Clone, Copy)]
pub struct Entry {
    /// Shipped default.
    pub value: f32,
    /// Debug slider lower bound.
    pub min: f32,
    /// Debug slider upper bound.
    pub max: f32,
    /// Debug slider increment.
    pub step: f32,
}

/// Registry loaded at startup; mutable so a debug overlay can tweak live.
#[derive(Resource)]
pub struct Params(HashMap<String, Entry>);

impl Params {
    /// Parse the embedded registry, skipping `_`-prefixed metadata keys.
    ///
    /// # Panics
    /// If `params.json` is malformed; that is a build error, not a runtime one.
    #[must_use]
    pub fn load() -> Self {
        let raw: HashMap<String, serde_json::Value> =
            serde_json::from_str(include_str!("../params.json")).expect("params.json parses");
        let entries = raw
            .into_iter()
            .filter(|(key, _)| !key.starts_with('_'))
            .map(|(key, value)| (key, serde_json::from_value(value).expect("registry entry shape")))
            .collect();
        Self(entries)
    }

    /// Current value of a tunable.
    ///
    /// # Panics
    /// On an unknown key: a typo is a bug, not a fallback case.
    #[must_use]
    pub fn get(&self, key: &str) -> f32 {
        self.0.get(key).unwrap_or_else(|| panic!("unknown param: {key}")).value
    }

    /// All tunable keys, for generating the debug overlay.
    pub fn keys(&self) -> impl Iterator<Item = &str> {
        self.0.keys().map(String::as_str)
    }
}
